# frozen_string_literal: true

require_relative 'parser'
require_relative 'fetcher'
# Generated by grpc_tools_ruby_protoc from
# /proto/worker/v1/worker.proto. The codegen script lives at
# scripts/gen-proto.sh (a follow-up). Uncomment once generated:
#
# require 'worker/v1/worker_pb'
# require 'worker/v1/worker_services_pb'

module RubyWorker
  # Service implements the universal `revund.worker.v1.Worker`
  # contract — the same contract ts-worker and php-worker speak.
  #
  # Each handler is thin — it translates between the gRPC wire
  # shape and the Parser domain object. The handler bodies are
  # written against the assumed generated message shape so
  # swapping the stub in is mechanical.
  class Service
    # include ::Revund::Worker::V1::Worker::Service

    NAME = 'ruby-worker'
    LANGUAGES = ['ruby'].freeze
    CAPABILITIES = %w[parse self_fetch].freeze

    # AUTH_HEADER mirrors the Go-side constant in
    # core/pkg/worker/auth.go. The bot stamps it on every
    # outbound RPC; this worker rejects requests without a
    # matching value when REVUND_WORKER_SECRET is configured.
    AUTH_HEADER = 'x-revund-worker-token'
    AUTH_SECRET_ENV = 'REVUND_WORKER_SECRET'

    def initialize
      @parser = RubyWorker::Parser.new
    end

    # Describe — self-identifies. The bot calls this on first
    # connect to learn what languages + capabilities this worker
    # advertises.
    def describe(_request, call)
      return unauthenticated!(call) unless authorized?(call)

      response_class = ::Revund::Worker::V1::DescribeResponse rescue nil
      return nil if response_class.nil?

      response_class.new(
        name: NAME,
        version: Server::VERSION,
        languages: LANGUAGES,
        capabilities: CAPABILITIES,
      )
    end

    def health(_request, call)
      return unauthenticated!(call) unless authorized?(call)

      response_class = ::Revund::Worker::V1::HealthResponse rescue nil
      return nil if response_class.nil?

      response_class.new(version: Server::VERSION)
    end

    def parse(request, call)
      return unauthenticated!(call) unless authorized?(call)

      response_class = ::Revund::Worker::V1::ParseResponse rescue nil
      return nil if response_class.nil?

      repo_path = resolve_repo_path(request)
      parsed = @parser.parse_files(repo_path, request.files.to_a)
      response_class.new(files: parsed)
    end

    private

    # Validate the bearer header against REVUND_WORKER_SECRET.
    # Empty / unset secret = no enforcement (CLI / local-dev
    # default). Returns true on success or "no enforcement."
    def authorized?(call)
      expected = ENV[AUTH_SECRET_ENV].to_s
      return true if expected.empty?

      md = call.respond_to?(:metadata) ? (call.metadata || {}) : {}
      Array(md[AUTH_HEADER]).first.to_s == expected
    end

    def unauthenticated!(_call)
      raise GRPC::Unauthenticated, 'missing or invalid x-revund-worker-token'
    end

    # Two dispatch modes:
    #   - shared-FS path mode: returns request.repo_path verbatim
    #   - self-fetch mode: hands the RepoSource to Fetcher, returns
    #     the local cached checkout path.
    def resolve_repo_path(request)
      src = request.respond_to?(:repo_source) ? request.repo_source : nil
      if src && !src.url.to_s.empty?
        return Fetcher.fetch_or_cache(
          url: src.url,
          ref: src.ref,
          auth_token: src.auth_token,
          auth_user: src.respond_to?(:auth_user) ? src.auth_user : '',
        )
      end
      request.repo_path
    end

    # ResolveSymbols and RunDiagnostics are intentionally not
    # implemented. The bot's caller checks the `capabilities`
    # list from Describe and skips RPCs the worker hasn't
    # advertised — so unimplemented = silently skipped.
  end
end
