# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: worker/v1/worker.proto for package 'revund.worker.v1'
# Original file comments:
# worker.proto — the universal AST-worker contract.
#
# # Public API
#
# This file defines the wire contract every Revund AST
# sidecar speaks. It is designed for STABILITY since the
# contract may eventually be published as an open-source
# interface that third-party language sidecars target.
#
# Compatibility rules:
#
#   - Adding fields to existing messages: ALLOWED (proto3
#     ignores unknown fields gracefully).
#   - Adding new RPCs: ALLOWED (clients negotiate capability
#     via Describe).
#   - Removing or renaming fields: BREAKING — bump the
#     package version (v1 → v2). Old clients keep speaking v1.
#   - Changing field types: BREAKING.
#
# # Sidecar contract
#
# A Revund worker is any process implementing this service.
# It can be:
#
#   - A first-party reference implementation we maintain
#     (ts-worker, php-worker, ruby-worker)
#   - A community-built sidecar for any language
#   - A proprietary worker a customer builds for their
#     in-house DSL
#
# The bot dials the worker by host:port, calls `Describe`
# to learn which languages + capabilities it advertises,
# and routes Parse RPCs based on the response. The bot
# does NOT hardcode language-to-worker mappings — every
# worker self-identifies.
#
# # Minimum viable worker
#
# Implement only `Describe`, `Health`, and `Parse`. Set
# `capabilities = ["parse"]`. The bot uses that worker for
# its advertised languages and skips the rest gracefully.
#
# # Symbol resolution / diagnostics (optional)
#
# Capabilities are advisory. Workers that ALSO support
# symbol resolution (returning declarations of identifiers
# referenced in changed code) advertise
# `capabilities = ["parse", "resolve_symbols"]`. Workers
# that run language-specific type-checkers (TypeScript's
# `tsc --noEmit`, PHP's PHPStan, Ruby's Sorbet) advertise
# `["parse", "diagnostics"]`. The bot uses these features
# when present, falls back to "just parse" when not.
#

require 'grpc'
require 'worker/v1/worker_pb'

module Revund
  module Worker
    module V1
      module Worker
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'revund.worker.v1.Worker'

          # Describe identifies the worker. The bot calls this
          # first to learn what languages + capabilities it
          # supports. Idempotent, side-effect-free.
          rpc :Describe, ::Revund::Worker::V1::DescribeRequest, ::Revund::Worker::V1::DescribeResponse
          # Health is a standard k8s-style liveness probe.
          rpc :Health, ::Revund::Worker::V1::HealthRequest, ::Revund::Worker::V1::HealthResponse
          # Parse returns a minimal AST view (imports + decls +
          # functions + concerns) for the requested files. Per-
          # file parse errors are returned INSIDE the response,
          # never as RPC errors. REQUIRED capability — every
          # healthy worker implements this.
          rpc :Parse, ::Revund::Worker::V1::ParseRequest, ::Revund::Worker::V1::ParseResponse
          # ResolveSymbols returns the declarations of identifiers
          # referenced in a diff but defined elsewhere in the
          # repo. Used by the bot's ingest layer to enrich the
          # LLM bundle with cross-file type information.
          #
          # OPTIONAL capability — workers advertise
          # "resolve_symbols" in Describe.Capabilities when
          # implemented. Workers that don't implement it return
          # UNIMPLEMENTED; the bot's caller checks the capability
          # list and skips the call when unsupported.
          rpc :ResolveSymbols, ::Revund::Worker::V1::ResolveRequest, ::Revund::Worker::V1::ResolveResponse
          # RunDiagnostics runs the language's native type-checker
          # (tsc --noEmit for TypeScript, PHPStan for PHP, Sorbet
          # for Ruby, etc.) and returns errors touching the
          # changed files. Empty when the project has no errors
          # or the worker doesn't run a type-checker — never an
          # RPC error.
          #
          # OPTIONAL capability — workers advertise "diagnostics"
          # in Describe.Capabilities when implemented.
          rpc :RunDiagnostics, ::Revund::Worker::V1::DiagnosticsRequest, ::Revund::Worker::V1::DiagnosticsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
